# This file was generated by go2nix.
{ stdenv, buildGoPackage, fetchgit, fetchhg, fetchbzr, fetchsvn }:

buildGoPackage rec {
  name = "matchbox-${version}";
  version = "20170502-${stdenv.lib.strings.substring 0 7 rev}";
  rev = "c2e5196d1acc5ce0682113871c6e44840b86cc4b";

  goPackagePath = "github.com/coreos/matchbox";

  src = fetchgit {
    inherit rev;
    url = "https://github.com/coreos/matchbox";
    sha256 = "0h3n8vn3zsf15s3c1dp04rh721ca59qpb3wdgspmc7s3wiawyia1";
  };

  # TODO: add metadata https://nixos.org/nixpkgs/manual/#sec-standard-meta-attributes
  meta = {
  };
}
